#pragma once

#include "OpenSimCreator/Graphics/CustomDecorationOptions.hpp"
#include "OpenSimCreator/Graphics/CustomRenderingOptions.hpp"

#include <oscar/Utils/UID.hpp>

#include <OpenSim/Common/ComponentPath.h>

namespace osc { class VirtualConstModelStatePair; }

namespace osc
{
    // parameters that affect which decorations shall be generated by a call
    // to `osc::GenerateModelSceneDecorations`
    //
    // effectively, this can be used to figure out whether new decorations need
    // to be generated
    struct ModelSceneDecorationsParams final {
        ModelSceneDecorationsParams();

        ModelSceneDecorationsParams(
            VirtualConstModelStatePair const&,
            CustomDecorationOptions const&,
            CustomRenderingOptions const&
        );

    private:
        friend bool operator==(ModelSceneDecorationsParams const&, ModelSceneDecorationsParams const&) noexcept;
        UID modelVersion;
        UID stateVersion;
    public:
        OpenSim::ComponentPath selection;
        OpenSim::ComponentPath hover;
        float fixupScaleFactor = 1.0f;
        CustomDecorationOptions decorationOptions;
        CustomRenderingOptions renderingOptions;
    };

    bool operator==(ModelSceneDecorationsParams const&, ModelSceneDecorationsParams const&) noexcept;
    bool operator!=(ModelSceneDecorationsParams const&, ModelSceneDecorationsParams const&) noexcept;
}