# error: valid toml, valid frame (grammar-wise), but logically invalid
#        because the provided axes are non-orthogonal

[frames]

    [frames.first]
    associated_mesh = "sphere.obj"
    origin_location = "LM2"
    axis_edge_begin = "LM2"
    axis_edge_end = "LM3"
    axis_edge_axis = "-x"
    nonparallel_edge_begin = "some_other_lm"
    nonparallel_edge_end = "another_one"
    cross_product_edge_axis = "+x"  # uh oh: non-orthogonal
