# basic file that a parser should be able to handle fine

[frames]

    [frames.first]
    associated_mesh = "sphere.obj"
    origin_location = "LM2"
    axis_edge_begin = "LM2"
    axis_edge_end = "LM3"
    axis_edge_axis = "-x"
    nonparallel_edge_begin = "LM4"
    nonparallel_edge_end = "LM4"  # uh oh
    cross_product_edge_axis = "+y"
