#pragma once

#include <liboscar/Graphics/AntiAliasingLevel.h>
#include <liboscar/Graphics/BlendingEquation.h>
#include <liboscar/Graphics/BlitFlags.h>
#include <liboscar/Graphics/Camera.h>
#include <liboscar/Graphics/CameraClearFlags.h>
#include <liboscar/Graphics/CameraClippingPlanes.h>
#include <liboscar/Graphics/CameraProjection.h>
#include <liboscar/Graphics/Color.h>
#include <liboscar/Graphics/ColorComponent.h>
#include <liboscar/Graphics/ColorHSLA.h>
#include <liboscar/Graphics/ColorRenderBufferFormat.h>
#include <liboscar/Graphics/ColorRenderBufferParams.h>
#include <liboscar/Graphics/ColorSpace.h>
#include <liboscar/Graphics/Color32.h>
#include <liboscar/Graphics/Cubemap.h>
#include <liboscar/Graphics/CubemapFace.h>
#include <liboscar/Graphics/CullMode.h>
#include <liboscar/Graphics/DepthFunction.h>
#include <liboscar/Graphics/DepthStencilRenderBufferFormat.h>
#include <liboscar/Graphics/DepthStencilRenderBufferParams.h>
#include <liboscar/Graphics/DestinationBlendingFactor.h>
#include <liboscar/Graphics/Geometries.h>
#include <liboscar/Graphics/Graphics.h>
#include <liboscar/Graphics/GraphicsContext.h>
#include <liboscar/Graphics/Material.h>
#include <liboscar/Graphics/Materials.h>
#include <liboscar/Graphics/MaterialPropertyBlock.h>
#include <liboscar/Graphics/Mesh.h>
#include <liboscar/Graphics/MeshFunctions.h>
#include <liboscar/Graphics/MeshIndicesView.h>
#include <liboscar/Graphics/MeshTopology.h>
#include <liboscar/Graphics/MeshUpdateFlags.h>
#include <liboscar/Graphics/RenderBufferLoadAction.h>
#include <liboscar/Graphics/RenderBufferStoreAction.h>
#include <liboscar/Graphics/RenderTarget.h>
#include <liboscar/Graphics/RenderTargetColorAttachment.h>
#include <liboscar/Graphics/RenderTargetDepthStencilAttachment.h>
#include <liboscar/Graphics/RenderTexture.h>
#include <liboscar/Graphics/RenderTextureParams.h>
#include <liboscar/Graphics/Rgba.h>
#include <liboscar/Graphics/Scene.h>
#include <liboscar/Graphics/Shader.h>
#include <liboscar/Graphics/ShaderPropertyType.h>
#include <liboscar/Graphics/SharedColorRenderBuffer.h>
#include <liboscar/Graphics/SharedDepthStencilRenderBuffer.h>
#include <liboscar/Graphics/Snorm.h>
#include <liboscar/Graphics/Snorm8.h>
#include <liboscar/Graphics/SourceBlendingFactor.h>
#include <liboscar/Graphics/SubMeshDescriptor.h>
#include <liboscar/Graphics/TextureComponentFormat.h>
#include <liboscar/Graphics/TextureDimensionality.h>
#include <liboscar/Graphics/TextureFilterMode.h>
#include <liboscar/Graphics/TextureFormat.h>
#include <liboscar/Graphics/Textures.h>
#include <liboscar/Graphics/TextureWrapMode.h>
#include <liboscar/Graphics/Texture2D.h>
#include <liboscar/Graphics/Unorm.h>
#include <liboscar/Graphics/Unorm8.h>
#include <liboscar/Graphics/VertexAttribute.h>
#include <liboscar/Graphics/VertexAttributeDescriptor.h>
#include <liboscar/Graphics/VertexAttributeFormat.h>
#include <liboscar/Graphics/VertexFormat.h>
