#pragma once

#include <liboscar/Maths/AABB.h>
#include <liboscar/Maths/AABBFunctions.h>
#include <liboscar/Maths/AnalyticPlane.h>
#include <liboscar/Maths/Angle.h>
#include <liboscar/Maths/BVH.h>
#include <liboscar/Maths/BVHCollision.h>
#include <liboscar/Maths/BVHNode.h>
#include <liboscar/Maths/BVHPrim.h>
#include <liboscar/Maths/Circle.h>
#include <liboscar/Maths/ClosedInterval.h>
#include <liboscar/Maths/CollisionTests.h>
#include <liboscar/Maths/CommonFunctions.h>
#include <liboscar/Maths/Constants.h>
#include <liboscar/Maths/CoordinateAxis.h>
#include <liboscar/Maths/CoordinateDirection.h>
#include <liboscar/Maths/Disc.h>
#include <liboscar/Maths/EasingFunctions.h>
#include <liboscar/Maths/Ellipsoid.h>
#include <liboscar/Maths/EulerAngles.h>
#include <liboscar/Maths/EulerPerspectiveCamera.h>
#include <liboscar/Maths/FrustumPlanes.h>
#include <liboscar/Maths/Functors.h>
#include <liboscar/Maths/GeometricFunctions.h>
#include <liboscar/Maths/LineSegment.h>
#include <liboscar/Maths/Matrix.h>
#include <liboscar/Maths/Matrix3x3.h>
#include <liboscar/Maths/Matrix4x4.h>
#include <liboscar/Maths/MatrixFunctions.h>
#include <liboscar/Maths/MathHelpers.h>
#include <liboscar/Maths/Negative.h>
#include <liboscar/Maths/Normalized.h>
#include <liboscar/Maths/Plane.h>
#include <liboscar/Maths/PlaneFunctions.h>
#include <liboscar/Maths/PolarPerspectiveCamera.h>
#include <liboscar/Maths/Qua.h>
#include <liboscar/Maths/Quat.h>
#include <liboscar/Maths/QuaternionFunctions.h>
#include <liboscar/Maths/Ray.h>
#include <liboscar/Maths/RayCollision.h>
#include <liboscar/Maths/Rect.h>
#include <liboscar/Maths/RectCorners.h>
#include <liboscar/Maths/RectFunctions.h>
#include <liboscar/Maths/Scalar.h>
#include <liboscar/Maths/Sphere.h>
#include <liboscar/Maths/Tetrahedron.h>
#include <liboscar/Maths/Transform.h>
#include <liboscar/Maths/TransformFunctions.h>
#include <liboscar/Maths/Triangle.h>
#include <liboscar/Maths/TriangleFunctions.h>
#include <liboscar/Maths/TrigonometricFunctions.h>
#include <liboscar/Maths/Vec.h>
#include <liboscar/Maths/Vec2.h>
#include <liboscar/Maths/Vec3.h>
#include <liboscar/Maths/Vec4.h>
#include <liboscar/Maths/VecFunctions.h>
