#pragma once

#include <liboscar/Concepts/AssociativeContainer.h>
#include <liboscar/Concepts/AssociativeContainerKey.h>
#include <liboscar/Concepts/BitCastable.h>
#include <liboscar/Concepts/ConvertibleToAnyOf.h>
#include <liboscar/Concepts/DereferencesTo.h>
#include <liboscar/Concepts/NamedInputStream.h>
#include <liboscar/Concepts/ObjectRepresentationByte.h>
#include <liboscar/Concepts/SameAsAnyOf.h>
#include <liboscar/DOM/Class.h>
#include <liboscar/DOM/Node.h>
#include <liboscar/DOM/NodePath.h>
#include <liboscar/DOM/Object.h>
#include <liboscar/DOM/PropertyInfo.h>
#include <liboscar/Formats/CSV.h>
#include <liboscar/Formats/DAE.h>
#include <liboscar/Formats/Image.h>
#include <liboscar/Formats/ImageLoadingFlags.h>
#include <liboscar/Formats/OBJ.h>
#include <liboscar/Formats/STL.h>
#include <liboscar/Formats/SVG.h>
#include <liboscar/Graphics/AntiAliasingLevel.h>
#include <liboscar/Graphics/BlendingEquation.h>
#include <liboscar/Graphics/BlitFlags.h>
#include <liboscar/Graphics/Camera.h>
#include <liboscar/Graphics/CameraClearFlags.h>
#include <liboscar/Graphics/CameraClippingPlanes.h>
#include <liboscar/Graphics/CameraProjection.h>
#include <liboscar/Graphics/Color.h>
#include <liboscar/Graphics/ColorComponent.h>
#include <liboscar/Graphics/ColorHSLA.h>
#include <liboscar/Graphics/ColorRenderBufferFormat.h>
#include <liboscar/Graphics/ColorRenderBufferParams.h>
#include <liboscar/Graphics/ColorSpace.h>
#include <liboscar/Graphics/Color32.h>
#include <liboscar/Graphics/Cubemap.h>
#include <liboscar/Graphics/CubemapFace.h>
#include <liboscar/Graphics/CullMode.h>
#include <liboscar/Graphics/DepthFunction.h>
#include <liboscar/Graphics/DepthStencilRenderBufferFormat.h>
#include <liboscar/Graphics/DepthStencilRenderBufferParams.h>
#include <liboscar/Graphics/DestinationBlendingFactor.h>
#include <liboscar/Graphics/Geometries/AABBGeometry.h>
#include <liboscar/Graphics/Geometries/BoxGeometry.h>
#include <liboscar/Graphics/Geometries/CircleGeometry.h>
#include <liboscar/Graphics/Geometries/CylinderGeometry.h>
#include <liboscar/Graphics/Geometries/ConeGeometry.h>
#include <liboscar/Graphics/Geometries/DodecahedronGeometry.h>
#include <liboscar/Graphics/Geometries/GridGeometry.h>
#include <liboscar/Graphics/Geometries/IcosahedronGeometry.h>
#include <liboscar/Graphics/Geometries/LatheGeometry.h>
#include <liboscar/Graphics/Geometries/OctahedronGeometry.h>
#include <liboscar/Graphics/Geometries/PlaneGeometry.h>
#include <liboscar/Graphics/Geometries/PolyhedronGeometry.h>
#include <liboscar/Graphics/Geometries/RingGeometry.h>
#include <liboscar/Graphics/Geometries/SolidGeometries.h>
#include <liboscar/Graphics/Geometries/SphereGeometry.h>
#include <liboscar/Graphics/Geometries/TetrahedronGeometry.h>
#include <liboscar/Graphics/Geometries/TorusGeometry.h>
#include <liboscar/Graphics/Geometries/TorusKnotGeometry.h>
#include <liboscar/Graphics/Geometries/WireframeGeometry.h>
#include <liboscar/Graphics/Graphics.h>
#include <liboscar/Graphics/GraphicsContext.h>
#include <liboscar/Graphics/Material.h>
#include <liboscar/Graphics/Materials/MeshBasicMaterial.h>
#include <liboscar/Graphics/Materials/MeshBasicTexturedMaterial.h>
#include <liboscar/Graphics/Materials/MeshDepthWritingMaterial.h>
#include <liboscar/Graphics/Materials/MeshPhongMaterial.h>
#include <liboscar/Graphics/MaterialPropertyBlock.h>
#include <liboscar/Graphics/Mesh.h>
#include <liboscar/Graphics/MeshFunctions.h>
#include <liboscar/Graphics/MeshIndicesView.h>
#include <liboscar/Graphics/MeshTopology.h>
#include <liboscar/Graphics/MeshUpdateFlags.h>
#include <liboscar/Graphics/RenderBufferLoadAction.h>
#include <liboscar/Graphics/RenderBufferStoreAction.h>
#include <liboscar/Graphics/RenderTarget.h>
#include <liboscar/Graphics/RenderTargetColorAttachment.h>
#include <liboscar/Graphics/RenderTargetDepthStencilAttachment.h>
#include <liboscar/Graphics/RenderTexture.h>
#include <liboscar/Graphics/RenderTextureParams.h>
#include <liboscar/Graphics/Rgba.h>
#include <liboscar/Graphics/Scene/CachedSceneRenderer.h>
#include <liboscar/Graphics/Scene/SceneCache.h>
#include <liboscar/Graphics/Scene/SceneCollision.h>
#include <liboscar/Graphics/Scene/SceneDecoration.h>
#include <liboscar/Graphics/Scene/SceneDecorationFlags.h>
#include <liboscar/Graphics/Scene/SceneDecorationShading.h>
#include <liboscar/Graphics/Scene/SceneHelpers.h>
#include <liboscar/Graphics/Scene/SceneRenderer.h>
#include <liboscar/Graphics/Scene/SceneRendererParams.h>
#include <liboscar/Graphics/Shader.h>
#include <liboscar/Graphics/ShaderPropertyType.h>
#include <liboscar/Graphics/SharedColorRenderBuffer.h>
#include <liboscar/Graphics/SharedDepthStencilRenderBuffer.h>
#include <liboscar/Graphics/Snorm.h>
#include <liboscar/Graphics/Snorm8.h>
#include <liboscar/Graphics/SourceBlendingFactor.h>
#include <liboscar/Graphics/SubMeshDescriptor.h>
#include <liboscar/Graphics/TextureComponentFormat.h>
#include <liboscar/Graphics/TextureDimensionality.h>
#include <liboscar/Graphics/TextureFilterMode.h>
#include <liboscar/Graphics/TextureFormat.h>
#include <liboscar/Graphics/Textures/ChequeredTexture.h>
#include <liboscar/Graphics/TextureWrapMode.h>
#include <liboscar/Graphics/Texture2D.h>
#include <liboscar/Graphics/Unorm.h>
#include <liboscar/Graphics/Unorm8.h>
#include <liboscar/Graphics/VertexAttribute.h>
#include <liboscar/Graphics/VertexAttributeDescriptor.h>
#include <liboscar/Graphics/VertexAttributeFormat.h>
#include <liboscar/Graphics/VertexFormat.h>
#include <liboscar/Maths/AABB.h>
#include <liboscar/Maths/AABBFunctions.h>
#include <liboscar/Maths/AnalyticPlane.h>
#include <liboscar/Maths/Angle.h>
#include <liboscar/Maths/BVH.h>
#include <liboscar/Maths/BVHCollision.h>
#include <liboscar/Maths/BVHNode.h>
#include <liboscar/Maths/BVHPrim.h>
#include <liboscar/Maths/Circle.h>
#include <liboscar/Maths/ClosedInterval.h>
#include <liboscar/Maths/CollisionTests.h>
#include <liboscar/Maths/CommonFunctions.h>
#include <liboscar/Maths/Constants.h>
#include <liboscar/Maths/CoordinateAxis.h>
#include <liboscar/Maths/CoordinateDirection.h>
#include <liboscar/Maths/Disc.h>
#include <liboscar/Maths/EasingFunctions.h>
#include <liboscar/Maths/Ellipsoid.h>
#include <liboscar/Maths/EulerAngles.h>
#include <liboscar/Maths/EulerPerspectiveCamera.h>
#include <liboscar/Maths/FrustumPlanes.h>
#include <liboscar/Maths/Functors.h>
#include <liboscar/Maths/GeometricFunctions.h>
#include <liboscar/Maths/LineSegment.h>
#include <liboscar/Maths/Matrix.h>
#include <liboscar/Maths/Matrix3x3.h>
#include <liboscar/Maths/Matrix4x4.h>
#include <liboscar/Maths/MatrixFunctions.h>
#include <liboscar/Maths/MathHelpers.h>
#include <liboscar/Maths/Negative.h>
#include <liboscar/Maths/Normalized.h>
#include <liboscar/Maths/Plane.h>
#include <liboscar/Maths/PlaneFunctions.h>
#include <liboscar/Maths/PolarPerspectiveCamera.h>
#include <liboscar/Maths/Qua.h>
#include <liboscar/Maths/Quaternion.h>
#include <liboscar/Maths/QuaternionFunctions.h>
#include <liboscar/Maths/Ray.h>
#include <liboscar/Maths/RayCollision.h>
#include <liboscar/Maths/Rect.h>
#include <liboscar/Maths/RectCorners.h>
#include <liboscar/Maths/RectFunctions.h>
#include <liboscar/Maths/Scalar.h>
#include <liboscar/Maths/Sphere.h>
#include <liboscar/Maths/Tetrahedron.h>
#include <liboscar/Maths/Transform.h>
#include <liboscar/Maths/TransformFunctions.h>
#include <liboscar/Maths/Triangle.h>
#include <liboscar/Maths/TriangleFunctions.h>
#include <liboscar/Maths/TrigonometricFunctions.h>
#include <liboscar/Maths/Vector.h>
#include <liboscar/Maths/Vector2.h>
#include <liboscar/Maths/Vector3.h>
#include <liboscar/Maths/Vector4.h>
#include <liboscar/Maths/VectorFunctions.h>
#include <liboscar/Platform/App.h>
#include <liboscar/Platform/AppClock.h>
#include <liboscar/Platform/AppMainLoopStatus.h>
#include <liboscar/Platform/AppMetadata.h>
#include <liboscar/Platform/AppSettings.h>
#include <liboscar/Platform/AppSettingScope.h>
#include <liboscar/Platform/Events/DisplayStateChangeEvent.h>
#include <liboscar/Platform/Events/DropFileEvent.h>
#include <liboscar/Platform/Events/Event.h>
#include <liboscar/Platform/Events/EventType.h>
#include <liboscar/Platform/Events/IEventListener.h>
#include <liboscar/Platform/Events/KeyEvent.h>
#include <liboscar/Platform/Events/MouseEvent.h>
#include <liboscar/Platform/Events/MouseWheelEvent.h>
#include <liboscar/Platform/Events/QuitEvent.h>
#include <liboscar/Platform/Events/TextInputEvent.h>
#include <liboscar/Platform/Events/WindowEvent.h>
#include <liboscar/Platform/Events/WindowEventType.h>
#include <liboscar/Platform/FileDialogFilter.h>
#include <liboscar/Platform/FileDialogResponse.h>
#include <liboscar/Platform/FilesystemResourceLoader.h>
#include <liboscar/Platform/ILogSink.h>
#include <liboscar/Platform/IResourceLoader.h>
#include <liboscar/Platform/Key.h>
#include <liboscar/Platform/KeyCombination.h>
#include <liboscar/Platform/KeyModifier.h>
#include <liboscar/Platform/Log.h>
#include <liboscar/Platform/Logger.h>
#include <liboscar/Platform/LogLevel.h>
#include <liboscar/Platform/LogMessage.h>
#include <liboscar/Platform/LogMessageView.h>
#include <liboscar/Platform/LogSink.h>
#include <liboscar/Platform/MouseButton.h>
#include <liboscar/Platform/MouseInputSource.h>
#include <liboscar/Platform/os.h>
#include <liboscar/Platform/ResourceDirectoryEntry.h>
#include <liboscar/Platform/ResourceLoader.h>
#include <liboscar/Platform/ResourcePath.h>
#include <liboscar/Platform/ResourceStream.h>
#include <liboscar/Platform/Screenshot.h>
#include <liboscar/Platform/ScreenshotAnnotation.h>
#include <liboscar/Platform/Widget.h>
#include <liboscar/Platform/WindowID.h>
#include <liboscar/Shims/Cpp20/stop_token.h>
#include <liboscar/Shims/Cpp20/thread.h>
#include <liboscar/Shims/Cpp23/numeric.h>
#include <liboscar/Shims/Cpp23/ranges.h>
#include <liboscar/Strings.h>
#include <liboscar/UI/Events/CloseTabEvent.h>
#include <liboscar/UI/Events/OpenNamedPanelEvent.h>
#include <liboscar/UI/Events/OpenPopupEvent.h>
#include <liboscar/UI/Events/OpenTabEvent.h>
#include <liboscar/UI/Events/ResetUIContextEvent.h>
#include <liboscar/UI/Icon.h>
#include <liboscar/UI/IconCache.h>
#include <liboscar/UI/MouseCapturingCamera.h>
#include <liboscar/UI/oscimgui.h>
#include <liboscar/UI/Panels/LogViewerPanel.h>
#include <liboscar/UI/Panels/Panel.h>
#include <liboscar/UI/Panels/PanelManager.h>
#include <liboscar/UI/Panels/PanelPrivate.h>
#include <liboscar/UI/Panels/PerfPanel.h>
#include <liboscar/UI/Panels/ToggleablePanelFlags.h>
#include <liboscar/UI/Panels/UndoRedoPanel.h>
#include <liboscar/UI/Popups/Popup.h>
#include <liboscar/UI/Popups/PopupManager.h>
#include <liboscar/UI/Popups/PopupPrivate.h>
#include <liboscar/UI/Popups/SaveChangesPopup.h>
#include <liboscar/UI/Popups/SaveChangesPopupConfig.h>
#include <liboscar/UI/Screens/TabTestingScreen.h>
#include <liboscar/UI/Tabs/CookiecutterTab.h>
#include <liboscar/UI/Tabs/ErrorTab.h>
#include <liboscar/UI/Tabs/ScreenshotTab.h>
#include <liboscar/UI/Tabs/Tab.h>
#include <liboscar/UI/Tabs/TabPrivate.h>
#include <liboscar/UI/Tabs/TabRegistry.h>
#include <liboscar/UI/Tabs/TabRegistryEntry.h>
#include <liboscar/UI/Widgets/CameraViewAxes.h>
#include <liboscar/UI/Widgets/GuiRuler.h>
#include <liboscar/UI/Widgets/IconWithMenu.h>
#include <liboscar/UI/Widgets/IconWithoutMenu.h>
#include <liboscar/UI/Widgets/LogViewer.h>
#include <liboscar/UI/Widgets/RedoButton.h>
#include <liboscar/UI/Widgets/SceneViewer.h>
#include <liboscar/UI/Widgets/UndoButton.h>
#include <liboscar/UI/Widgets/WindowMenu.h>
#include <liboscar/Utils/Algorithms.h>
#include <liboscar/Utils/Assertions.h>
#include <liboscar/Utils/BitwiseHelpers.h>
#include <liboscar/Utils/ChronoHelpers.h>
#include <liboscar/Utils/CircularBuffer.h>
#include <liboscar/Utils/ClonePtr.h>
#include <liboscar/Utils/Conversion.h>
#include <liboscar/Utils/CopyOnUpdPtr.h>
#include <liboscar/Utils/CStringView.h>
#include <liboscar/Utils/DefaultConstructOnCopy.h>
#include <liboscar/Utils/EnumHelpers.h>
#include <liboscar/Utils/ExceptionHelpers.h>
#include <liboscar/Utils/FileChangePoller.h>
#include <liboscar/Utils/FilenameExtractor.h>
#include <liboscar/Utils/FilesystemHelpers.h>
#include <liboscar/Utils/Flags.h>
#include <liboscar/Utils/HashHelpers.h>
#include <liboscar/Utils/LifetimedPtr.h>
#include <liboscar/Utils/LifetimeWatcher.h>
#include <liboscar/Utils/NonTypelist.h>
#include <liboscar/Utils/NullOStream.h>
#include <liboscar/Utils/NullStreambuf.h>
#include <liboscar/Utils/ObjectRepresentation.h>
#include <liboscar/Utils/ParalellizationHelpers.h>
#include <liboscar/Utils/Perf.h>
#include <liboscar/Utils/PerfClock.h>
#include <liboscar/Utils/PerfMeasurement.h>
#include <liboscar/Utils/PerfMeasurementMetadata.h>
#include <liboscar/Utils/ScopedLifetime.h>
#include <liboscar/Utils/ScopeExit.h>
#include <liboscar/Utils/SharedLifetimeBlock.h>
#include <liboscar/Utils/SharedPreHashedString.h>
#include <liboscar/Utils/Spsc.h>
#include <liboscar/Utils/StdVariantHelpers.h>
#include <liboscar/Utils/StringHelpers.h>
#include <liboscar/Utils/StringName.h>
#include <liboscar/Utils/SynchronizedValue.h>
#include <liboscar/Utils/SynchronizedValueGuard.h>
#include <liboscar/Utils/TemporaryFile.h>
#include <liboscar/Utils/TemporaryFileParameters.h>
#include <liboscar/Utils/TransparentStringHasher.h>
#include <liboscar/Utils/TypeInfoReference.h>
#include <liboscar/Utils/Typelist.h>
#include <liboscar/Utils/UID.h>
#include <liboscar/Utils/UndoRedo.h>
#include <liboscar/Utils/VariableLengthArray.h>
#include <liboscar/Utils/WatchableLifetime.h>
#include <liboscar/Variant/Variant.h>
#include <liboscar/Variant/VariantType.h>
#include <liboscar/Variant/VariantTypeList.h>
#include <liboscar/Variant/VariantTypeTraits.h>
