#pragma once

#include <liboscar/Platform/App.h>
#include <liboscar/Platform/AppClock.h>
#include <liboscar/Platform/AppMainLoopStatus.h>
#include <liboscar/Platform/AppMetadata.h>
#include <liboscar/Platform/AppSettings.h>
#include <liboscar/Platform/AppSettingScope.h>
#include <liboscar/Platform/Events.h>
#include <liboscar/Platform/FileDialogFilter.h>
#include <liboscar/Platform/FileDialogResponse.h>
#include <liboscar/Platform/FilesystemResourceLoader.h>
#include <liboscar/Platform/IconCodepoints.h>
#include <liboscar/Platform/ILogSink.h>
#include <liboscar/Platform/IResourceLoader.h>
#include <liboscar/Platform/Key.h>
#include <liboscar/Platform/KeyModifier.h>
#include <liboscar/Platform/Log.h>
#include <liboscar/Platform/Logger.h>
#include <liboscar/Platform/LogLevel.h>
#include <liboscar/Platform/LogMessage.h>
#include <liboscar/Platform/LogMessageView.h>
#include <liboscar/Platform/LogSink.h>
#include <liboscar/Platform/Monitor.h>
#include <liboscar/Platform/MouseButton.h>
#include <liboscar/Platform/MouseInputSource.h>
#include <liboscar/Platform/os.h>
#include <liboscar/Platform/ResourceDirectoryEntry.h>
#include <liboscar/Platform/ResourceLoader.h>
#include <liboscar/Platform/ResourcePath.h>
#include <liboscar/Platform/ResourceStream.h>
#include <liboscar/Platform/Screen.h>
#include <liboscar/Platform/ScreenPrivate.h>
#include <liboscar/Platform/Screenshot.h>
#include <liboscar/Platform/ScreenshotAnnotation.h>
#include <liboscar/Platform/Widget.h>
#include <liboscar/Platform/WindowID.h>
