#pragma once

#include <liboscar/Utils/Algorithms.h>
#include <liboscar/Utils/Assertions.h>
#include <liboscar/Utils/ChronoHelpers.h>
#include <liboscar/Utils/CircularBuffer.h>
#include <liboscar/Utils/ClonePtr.h>
#include <liboscar/Utils/Concepts.h>
#include <liboscar/Utils/Conversion.h>
#include <liboscar/Utils/CopyOnUpdPtr.h>
#include <liboscar/Utils/CStringView.h>
#include <liboscar/Utils/DefaultConstructOnCopy.h>
#include <liboscar/Utils/EnumHelpers.h>
#include <liboscar/Utils/ExceptionHelpers.h>
#include <liboscar/Utils/FileChangePoller.h>
#include <liboscar/Utils/FilenameExtractor.h>
#include <liboscar/Utils/FilesystemHelpers.h>
#include <liboscar/Utils/Flags.h>
#include <liboscar/Utils/HashHelpers.h>
#include <liboscar/Utils/LifetimedPtr.h>
#include <liboscar/Utils/LifetimeWatcher.h>
#include <liboscar/Utils/NonTypelist.h>
#include <liboscar/Utils/NullOStream.h>
#include <liboscar/Utils/NullStreambuf.h>
#include <liboscar/Utils/ObjectRepresentation.h>
#include <liboscar/Utils/ParalellizationHelpers.h>
#include <liboscar/Utils/Perf.h>
#include <liboscar/Utils/PerfClock.h>
#include <liboscar/Utils/PerfMeasurement.h>
#include <liboscar/Utils/PerfMeasurementMetadata.h>
#include <liboscar/Utils/ScopedLifetime.h>
#include <liboscar/Utils/ScopeGuard.h>
#include <liboscar/Utils/SharedLifetimeBlock.h>
#include <liboscar/Utils/SharedPreHashedString.h>
#include <liboscar/Utils/Spsc.h>
#include <liboscar/Utils/StdVariantHelpers.h>
#include <liboscar/Utils/StringHelpers.h>
#include <liboscar/Utils/StringName.h>
#include <liboscar/Utils/SynchronizedValue.h>
#include <liboscar/Utils/SynchronizedValueGuard.h>
#include <liboscar/Utils/TemporaryFile.h>
#include <liboscar/Utils/TemporaryFileParameters.h>
#include <liboscar/Utils/TransparentStringHasher.h>
#include <liboscar/Utils/TypeInfoReference.h>
#include <liboscar/Utils/Typelist.h>
#include <liboscar/Utils/UID.h>
#include <liboscar/Utils/UndoRedo.h>
// #include <liboscar/Utils/VariableLengthArray.h>  // TODO: reenable once MacOS gets pmr::memory_resource support
#include <liboscar/Utils/WatchableLifetime.h>
