resources = "resources"
docs = "share/doc/html"

# change this if you need OSC to print more information to the log
# log_level = "trace"  # trace < debug < info < warn < err < critical

# handy for auto-opening an in-development tab
# initial_tab = "LearnOpenGL/Blending"

[experimental_feature_flags]

# change this to tell the application that it can use high-DPI mode
#
# note: extremely experimental, because the codebase isn't high-DPI aware (yet)
# high_dpi_mode = true