# landmark-based frame definitions for frames in the associated
# OpenSim model

[frames]

    # a frame must be identified using a full abspath to the associated
    # frame in the OpenSim model (it's unambiguous, because user models
    # might contain offset frames to bodies that are named the same (e.g.
    # two called "pelvis_offset"))
    [frames."/jointset/weldjoint/ground_offset"]
    associated_mesh = "sphere.obj"
    origin_location = "LM2"
    axis_edge_begin = "LM2"
    axis_edge_end = "LM3"
    axis_edge_axis = "-x"
    nonparallel_edge_begin = "some_other_lm"
    nonparallel_edge_end = "another_one"
    cross_product_edge_axis = "+y"
