from PIL import Image
import os

# AK: this was initially generated by ChatGPT and I just played around with it a little

def resize_png_files(directory, scale_factor=0.5):
    for root, dirs, files in os.walk(directory):
        for filename in files:
            if filename.lower().endswith('.png'):
                file_path = os.path.join(root, filename)

                # Open the image
                with Image.open(file_path) as img:
                    # Calculate new dimensions based on the scale factor
                    new_width = int(img.width * scale_factor)
                    new_height = int(img.height * scale_factor)

                    print(f'resizing {file_path}: ({img.width}, {img.height}) --> ({new_width}, {new_height})')

                    # Resize the image
                    resized_img = img.resize((new_width, new_height))

                    # Save the resized image, overwriting the original file
                    resized_img.save(file_path)

if __name__ == "__main__":
    # Replace 'your_directory_path' with the path to your main directory
    main_directory_path = 'resources/oscar_learnopengl/textures/pbr'

    # Specify the scale factor for resizing (e.g., 0.5 for 50%)
    scale_factor = 0.5

    # Call the function to recursively resize PNG files in the specified directory
    resize_png_files(main_directory_path, scale_factor)
