#pragma once

#include <oscar/Graphics/AntiAliasingLevel.h>
#include <oscar/Graphics/BlendingEquation.h>
#include <oscar/Graphics/BlitFlags.h>
#include <oscar/Graphics/Camera.h>
#include <oscar/Graphics/CameraClearFlags.h>
#include <oscar/Graphics/CameraClippingPlanes.h>
#include <oscar/Graphics/CameraProjection.h>
#include <oscar/Graphics/Color.h>
#include <oscar/Graphics/ColorHSLA.h>
#include <oscar/Graphics/ColorRenderBufferFormat.h>
#include <oscar/Graphics/ColorRenderBufferParams.h>
#include <oscar/Graphics/ColorSpace.h>
#include <oscar/Graphics/Color32.h>
#include <oscar/Graphics/Cubemap.h>
#include <oscar/Graphics/CubemapFace.h>
#include <oscar/Graphics/CullMode.h>
#include <oscar/Graphics/DepthFunction.h>
#include <oscar/Graphics/DepthStencilRenderBufferFormat.h>
#include <oscar/Graphics/DepthStencilRenderBufferParams.h>
#include <oscar/Graphics/DestinationBlendingFactor.h>
#include <oscar/Graphics/Geometries.h>
#include <oscar/Graphics/Graphics.h>
#include <oscar/Graphics/GraphicsContext.h>
#include <oscar/Graphics/Material.h>
#include <oscar/Graphics/Materials.h>
#include <oscar/Graphics/MaterialPropertyBlock.h>
#include <oscar/Graphics/Mesh.h>
#include <oscar/Graphics/MeshFunctions.h>
#include <oscar/Graphics/MeshIndicesView.h>
#include <oscar/Graphics/MeshTopology.h>
#include <oscar/Graphics/MeshUpdateFlags.h>
#include <oscar/Graphics/RenderBufferLoadAction.h>
#include <oscar/Graphics/RenderBufferReadWrite.h>
#include <oscar/Graphics/RenderBufferStoreAction.h>
#include <oscar/Graphics/RenderTarget.h>
#include <oscar/Graphics/RenderTargetColorAttachment.h>
#include <oscar/Graphics/RenderTargetDepthStencilAttachment.h>
#include <oscar/Graphics/RenderTexture.h>
#include <oscar/Graphics/RenderTextureParams.h>
#include <oscar/Graphics/Scene.h>
#include <oscar/Graphics/Shader.h>
#include <oscar/Graphics/ShaderPropertyType.h>
#include <oscar/Graphics/SharedColorRenderBuffer.h>
#include <oscar/Graphics/SharedDepthStencilRenderBuffer.h>
#include <oscar/Graphics/Snorm.h>
#include <oscar/Graphics/Snorm8.h>
#include <oscar/Graphics/SourceBlendingFactor.h>
#include <oscar/Graphics/SubMeshDescriptor.h>
#include <oscar/Graphics/TextureChannelFormat.h>
#include <oscar/Graphics/TextureDimensionality.h>
#include <oscar/Graphics/TextureFilterMode.h>
#include <oscar/Graphics/TextureFormat.h>
#include <oscar/Graphics/Textures.h>
#include <oscar/Graphics/TextureWrapMode.h>
#include <oscar/Graphics/Texture2D.h>
#include <oscar/Graphics/Unorm.h>
#include <oscar/Graphics/Unorm8.h>
#include <oscar/Graphics/VertexAttribute.h>
#include <oscar/Graphics/VertexAttributeDescriptor.h>
#include <oscar/Graphics/VertexAttributeFormat.h>
#include <oscar/Graphics/VertexFormat.h>
