#pragma once

#include <oscar/Graphics/AntiAliasingLevel.hpp>
#include <oscar/Graphics/BlitFlags.hpp>
#include <oscar/Graphics/Camera.hpp>
#include <oscar/Graphics/CameraClearFlags.hpp>
#include <oscar/Graphics/CameraProjection.hpp>
#include <oscar/Graphics/Color.hpp>
#include <oscar/Graphics/ColorHSLA.hpp>
#include <oscar/Graphics/ColorSpace.hpp>
#include <oscar/Graphics/Color32.hpp>
#include <oscar/Graphics/Cubemap.hpp>
#include <oscar/Graphics/CubemapFace.hpp>
#include <oscar/Graphics/CullMode.hpp>
#include <oscar/Graphics/DepthFunction.hpp>
#include <oscar/Graphics/DepthStencilFormat.hpp>
#include <oscar/Graphics/Graphics.hpp>
#include <oscar/Graphics/GraphicsContext.hpp>
#include <oscar/Graphics/GraphicsHelpers.hpp>
#include <oscar/Graphics/ImageLoadingFlags.hpp>
#include <oscar/Graphics/Material.hpp>
#include <oscar/Graphics/MaterialPropertyBlock.hpp>
#include <oscar/Graphics/Mesh.hpp>
#include <oscar/Graphics/MeshGenerators.hpp>
#include <oscar/Graphics/MeshIndicesView.hpp>
#include <oscar/Graphics/MeshTopology.hpp>
#include <oscar/Graphics/MeshUpdateFlags.hpp>
#include <oscar/Graphics/RenderBuffer.hpp>
#include <oscar/Graphics/RenderBufferLoadAction.hpp>
#include <oscar/Graphics/RenderBufferStoreAction.hpp>
#include <oscar/Graphics/RenderBufferType.hpp>
#include <oscar/Graphics/RenderTarget.hpp>
#include <oscar/Graphics/RenderTargetAttachment.hpp>
#include <oscar/Graphics/RenderTargetColorAttachment.hpp>
#include <oscar/Graphics/RenderTargetDepthAttachment.hpp>
#include <oscar/Graphics/RenderTexture.hpp>
#include <oscar/Graphics/RenderTextureDescriptor.hpp>
#include <oscar/Graphics/RenderTextureFormat.hpp>
#include <oscar/Graphics/RenderTextureReadWrite.hpp>
#include <oscar/Graphics/Shader.hpp>
#include <oscar/Graphics/ShaderCache.hpp>
#include <oscar/Graphics/ShaderPropertyType.hpp>
#include <oscar/Graphics/SubMeshDescriptor.hpp>
#include <oscar/Graphics/TextureChannelFormat.hpp>
#include <oscar/Graphics/TextureDimensionality.hpp>
#include <oscar/Graphics/TextureFilterMode.hpp>
#include <oscar/Graphics/TextureFormat.hpp>
#include <oscar/Graphics/TextureGenerators.hpp>
#include <oscar/Graphics/TextureWrapMode.hpp>
#include <oscar/Graphics/Texture2D.hpp>
#include <oscar/Graphics/Unorm8.hpp>
#include <oscar/Graphics/VertexAttribute.hpp>
#include <oscar/Graphics/VertexAttributeDescriptor.hpp>
#include <oscar/Graphics/VertexAttributeFormat.hpp>
#include <oscar/Graphics/VertexFormat.hpp>
