#pragma once

#include <oscar/Maths/AABB.hpp>
#include <oscar/Maths/Angle.hpp>
#include <oscar/Maths/BVH.hpp>
#include <oscar/Maths/BVHCollision.hpp>
#include <oscar/Maths/BVHNode.hpp>
#include <oscar/Maths/BVHPrim.hpp>
#include <oscar/Maths/Circle.hpp>
#include <oscar/Maths/CollisionTests.hpp>
#include <oscar/Maths/Disc.hpp>
#include <oscar/Maths/EasingFunctions.hpp>
#include <oscar/Maths/Ellipsoid.hpp>
#include <oscar/Maths/EulerPerspectiveCamera.hpp>
#include <oscar/Maths/Eulers.hpp>
#include <oscar/Maths/LengthType.hpp>
#include <oscar/Maths/Line.hpp>
#include <oscar/Maths/Mat.hpp>
#include <oscar/Maths/MathHelpers.hpp>
#include <oscar/Maths/Mat3.hpp>
#include <oscar/Maths/Mat4.hpp>
#include <oscar/Maths/Mat4x3.hpp>
#include <oscar/Maths/Plane.hpp>
#include <oscar/Maths/PointDirection.hpp>
#include <oscar/Maths/PolarPerspectiveCamera.hpp>
#include <oscar/Maths/Qua.hpp>
#include <oscar/Maths/Qualifier.hpp>
#include <oscar/Maths/Quat.hpp>
#include <oscar/Maths/RayCollision.hpp>
#include <oscar/Maths/Rect.hpp>
#include <oscar/Maths/Segment.hpp>
#include <oscar/Maths/Sphere.hpp>
#include <oscar/Maths/Tetrahedron.hpp>
#include <oscar/Maths/Transform.hpp>
#include <oscar/Maths/Triangle.hpp>
#include <oscar/Maths/UnitVec.hpp>
#include <oscar/Maths/UnitVec3.hpp>
#include <oscar/Maths/Vec.hpp>
#include <oscar/Maths/Vec2.hpp>
#include <oscar/Maths/Vec3.hpp>
#include <oscar/Maths/Vec4.hpp>
