#pragma once

#include <oscar/Maths/AABB.h>
#include <oscar/Maths/Angle.h>
#include <oscar/Maths/BVH.h>
#include <oscar/Maths/BVHCollision.h>
#include <oscar/Maths/BVHNode.h>
#include <oscar/Maths/BVHPrim.h>
#include <oscar/Maths/Circle.h>
#include <oscar/Maths/CollisionTests.h>
#include <oscar/Maths/CommonFunctions.h>
#include <oscar/Maths/Constants.h>
#include <oscar/Maths/Disc.h>
#include <oscar/Maths/EasingFunctions.h>
#include <oscar/Maths/Ellipsoid.h>
#include <oscar/Maths/EulerPerspectiveCamera.h>
#include <oscar/Maths/Eulers.h>
#include <oscar/Maths/FrameAxis.h>
#include <oscar/Maths/Functors.h>
#include <oscar/Maths/GeometricFunctions.h>
#include <oscar/Maths/Line.h>
#include <oscar/Maths/Mat.h>
#include <oscar/Maths/MatFunctions.h>
#include <oscar/Maths/MathHelpers.h>
#include <oscar/Maths/Mat3.h>
#include <oscar/Maths/Mat4.h>
#include <oscar/Maths/Plane.h>
#include <oscar/Maths/PointDirection.h>
#include <oscar/Maths/PolarPerspectiveCamera.h>
#include <oscar/Maths/Qua.h>
#include <oscar/Maths/Quat.h>
#include <oscar/Maths/QuaternionFunctions.h>
#include <oscar/Maths/RayCollision.h>
#include <oscar/Maths/Rect.h>
#include <oscar/Maths/Segment.h>
#include <oscar/Maths/Sphere.h>
#include <oscar/Maths/Tetrahedron.h>
#include <oscar/Maths/Transform.h>
#include <oscar/Maths/TransformFunctions.h>
#include <oscar/Maths/Triangle.h>
#include <oscar/Maths/TriangleFunctions.h>
#include <oscar/Maths/TrigonometricFunctions.h>
#include <oscar/Maths/UnitVec.h>
#include <oscar/Maths/UnitVec3.h>
#include <oscar/Maths/Vec.h>
#include <oscar/Maths/VecFunctions.h>
#include <oscar/Maths/Vec2.h>
#include <oscar/Maths/Vec3.h>
#include <oscar/Maths/Vec4.h>
