on: [push]

env:
  # Bake a GitHub build ID into the binary so that there's a way of looking
  # up the build logs for a build via GitHub Actions' UI/API.
  OSC_BUILD_ID: "GITHUB_${{ github.run_id }}.${{ github.run_number }}"

jobs:

  windows_amd64:
    name: Windows (amd64)
    runs-on: windows-2022
    env:
      # Filter out tests that require OpenGL 3.3 support (GitHub Windows
      # runner doesn't support it).
      OSC_TEST_EXCLUDE_FILTER: "Graphics|MeshDepthWritingMaterialFixture|MeshNormalVectorsMaterialFixture|ShaderTest|MaterialTest|RegisteredDemoTabsTest|RegisteredOpenSimCreatorTabs|AddComponentPopup|LoadingTab"
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Setup Python Virtual Environment
      shell: cmd
      run: cd %GITHUB_WORKSPACE% && python -m venv .venv && call .venv\Scripts\activate && pip install -r requirements\all_requirements.txt

    - name: Build OpenSim Creator Dependencies
      shell: cmd
      run: cd %GITHUB_WORKSPACE%/third_party && call opynsim/scripts/env_vs-x64.bat && cmake --workflow --preset Release-Windows-amd64

    - name: Build OpenSim Creator
      shell: cmd
      run: cd %GITHUB_WORKSPACE% && call third_party/opynsim/scripts/env_vs-x64.bat && cmake --workflow --preset Release-Windows-amd64

    - uses: actions/upload-artifact@v4
      with:
        name: opensimcreator-windows-amd64-msi
        path: build/Release-Windows-amd64/*windows-amd64.msi
        if-no-files-found: error

    - uses: actions/upload-artifact@v4
      with:
        name: opensimcreator-windows-amd64-zip
        path: build/Release-Windows-amd64/*windows-amd64.zip
        if-no-files-found: error

  macos_amd64:
    name: MacOS (amd64)
    runs-on: macos-14
    env:
      CTEST_PARALLEL_LEVEL: 1
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Setup Python Virtual Environment
      run: cd ${GITHUB_WORKSPACE} && python -m venv .venv && source .venv/bin/activate && pip install -r requirements/all_requirements.txt

    - name: Build OpenSim Creator Dependencies
      run: cd ${GITHUB_WORKSPACE}/third_party && cmake --workflow --preset Release-MacOS-amd64

    - name: Build OpenSim Creator
      run: cd ${GITHUB_WORKSPACE} && cmake --workflow --preset Release-MacOS-amd64

    - uses: actions/upload-artifact@v4
      with:
        name: opensimcreator-macos-amd64-dmg
        path: build/Release-MacOS-amd64/*.dmg
        if-no-files-found: error

  macos_arm64:
    name: MacOS (arm64)
    runs-on: macos-14
    env:
      CTEST_PARALLEL_LEVEL: 1
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Setup Python Virtual Environment
      run: cd ${GITHUB_WORKSPACE} && python -m venv .venv && source .venv/bin/activate && pip install -r requirements/all_requirements.txt

    - name: Build OpenSim Creator Dependencies
      run: cd ${GITHUB_WORKSPACE}/third_party && cmake --workflow --preset Release-MacOS-arm64

    - name: Build OpenSim Creator
      run: cd ${GITHUB_WORKSPACE} && cmake --workflow --preset Release-MacOS-arm64

    - uses: actions/upload-artifact@v4
      with:
        name: opensimcreator-macos-arm64-dmg
        path: build/Release-MacOS-arm64/*.dmg
        if-no-files-found: error

  almalinux18_amd64:
    name: AlmaLinux 8 (amd64, docker)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build OS (AlmaLinux8) Docker Image
      run: cd ${GITHUB_WORKSPACE}/third_party/opynsim/docker && docker build -f almalinux8.Dockerfile -t opynsim:almalinux8 .

    - name: Setup Python Virtual Environment
      run: docker run --rm -v ${GITHUB_WORKSPACE}:/workspace -w /workspace opynsim:almalinux8 /bin/bash -c "python3.12 -m venv .venv && source .venv/bin/activate && pip install -r requirements/all_requirements.txt"

    - name: Build OpenSim Creator Dependencies
      run: docker run --rm -v ${GITHUB_WORKSPACE}:/workspace -w /workspace opynsim:almalinux8 /bin/bash -c "cd third_party && cmake --workflow --preset Release-Linux-amd64"

    - name: Build OpenSim Creator
      run: docker run --rm -v ${GITHUB_WORKSPACE}:/workspace -w /workspace opynsim:almalinux8 /bin/bash -c "xvfb-run cmake --workflow --preset Release-Linux-amd64"

    - uses: actions/upload-artifact@v4
      with:
        name: opensimcreator-linux-amd64-deb
        path: build/Release-Linux-amd64/*.deb
        if-no-files-found: error

    - uses: actions/upload-artifact@v4
      with:
        name: opensimcreator-linux-amd64-tarxz
        path: build/Release-Linux-amd64/*.tar.xz
        if-no-files-found: error
